### ISSUE TITLE
Do I need to specify `N2` in `richardson_number_ccf!`?

### ISSUE THREAD

**Issue by ali-ramadhan** [tomchor/Oceanostics.jl#1]
Just wanted to make sure that in `richardson_number_ccf!` is `N2` the stratification of the base/reference state?

So if my LES is solving for the full velocities (no background/base state) then I should set `dUdz_bg = 0`, `dVdz_bg = 0` and `N2 = 0`?

https://github.com/tomchor/Oceanostics.jl/blob/81d48c323f38f38617ed162e320d14c1691a615f/src/FlowDiagnostics.jl#L7-L15

**Comment by tomchor** [comment]
That's correct! I tried to make these scripts as general as possible and I tend to use background fields a lot. So basically I included `N2`, `dUdz_bg` and `dVdz_bg` to make room for possible `BackgroundField`s. (Although you can obviously use it for other purposes.)

Maybe I should be more consistent and change from `N2` to `N2_bg`? And from `dBdz` to `dBdz_tot`?

**Comment by ali-ramadhan** [comment]
Ah I think it's fine! I don't usually run with background states but will soon. But yeah `N2_bg` might be clearer for future users!

**Comment by ali-ramadhan** [comment]
Ah while I'm here, how do you use `richardson_number_ccf!` with `KernelComputedField`?

It seems you can pass parameters to a `KernelComputedField` but not sure how to pass `dUdz_bg, dVdz_bg, N2`.

Should the function signature be changed to
```julia
richardson_number_ccf!(Ri, grid, u, v, b, bg_params) 
```
then we do
```julia
Ri = KernelComputedField(Center, Center, Face, Oceanostics.FlowDiagnostics.richardson_number_ccf!, model, field_dependencies=(u, v, b), parameters=(dUdz_bg=0, dVdz_bg=0, N2_bg=0))
```
?

**Comment by tomchor** [comment]
I haven't tried that, but that might be the best approach. I always (very erroneously) call it as

```julia
Ri = KernelComputedField(Center, Center, Face, richardson_number_ccf!, model;
                         field_dependencies=(u_tot, v, b_tot, 0, 0, 0))
```
which I am not proud of haha

Feel free to make the change if you want! Otherwise I'll do it whenever I have the time to test it

**Comment by ali-ramadhan** [comment]
Ah neat that makes sense! I'll do that for now.

Thanks for the quick reply!

**Comment by tomchor** [comment]
Ah, I remember why I haven't changed that!

If I understand `KernelComputedField` correctly, the difference between something in the `field_depencies` and `parameters` is that we `compute!` anything in `field_dependencies`:

https://github.com/CliMA/Oceananigans.jl/blob/df9b830e574261efb1b7b0ee43b783be2381ceaf/src/Fields/kernel_computed_field.jl#L76-L80

So I think if you don't have a background and just want to set those to zero (or any constant value), it's okay to leave it as a parameter. But maybe if you have a background that's not a constant you might want to compute it? I was meaning to test the behavior there, but life got too busy and I didn't have time.

Thoughts?

cc @glwagner

**Comment by ali-ramadhan** [comment]
Ah I think that makes sense! So right now it only uses numbers for the background state derivatives but you might want to dispatch on whether the background state is a number or field in the future:

```julia
richardson_number_ccf!(Ri, grid, u, v, b, dUdz_bg::Number, dVdz_bg::Number, N2_bg::Number)
```

and

```julia
richardson_number_ccf!(Ri, grid, u, v, b, dUdz_bg::AbstractField, dVdz_bg::AbstractField, N2_bg::AbstractField) 
```

**Comment by tomchor** [comment]
> you might want to dispatch on whether the background state is a number or field in the future:

That's a good point. I'm not familiar enough with multiple dispatch to foresee to implications on `KernelComputedField`s, but it seems like a good idea.

Also, thinking more about it I actually think we _should_ make the change you suggested and create of tuple for constant background fields. If the background gradients aren't constant we can always add them to the model fields and pass a binary operation to be computed. Unless I'm missing something, I think it actually makes things simpler. If you have a background field that is constant you can use 

```julia
Ri = KernelComputedField(Center, Center, Face, richardson_number_ccf!, model;
                         field_dependencies=(u, v, b), parameters=(0, 0, N2_constant))
```

and save yourself some computations. If you're using a background that isn't constant then you can do
```julia
Ri = KernelComputedField(Center, Center, Face, richardson_number_ccf!, model;
                         field_dependencies=(u, v, b + model.background_fields.tracers.b), parameters=(0, 0, 0))
```

Agree?

**Comment by ali-ramadhan** [comment]
Ah I like your suggestion. Looks like it should work whether the background is a number or a field, and you only need to define one kernel!

**Comment by tomchor** [comment]
Yes! I've tested this behavior in my scripts and it seems to always work :+1:, so making the change to `bg_parameters` is the way to go I think.
