### ISSUE TITLE
Register new version

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#10]
@JuliaRegistrator register

**Comment by tomchor** [comment]
@JuliaRegistrator register()

**Comment by tomchor** [comment]
@ali-ramadhan am I making some mistake here? For some reason I can't trigger the registrator!

**Comment by tomchor** [comment]
@JuliaRegistrator register

**Comment by DilumAluthge** [comment]
@juliaregistrator register

**Comment by DilumAluthge** [comment]
So the bot is definitely installed.

@nkottary

**Comment by nkottary** [comment]
@tomchor Can you try `JuliaRegistrator register branch=main`? I will look at how to make the bot pick up the default branch.

**Comment by nkottary** [comment]
Should be fixed by https://github.com/JuliaRegistries/Registrator.jl/pull/328

**Comment by tomchor** [comment]
@JuliaRegistrator register branch=main

**Comment by tomchor** [comment]
@nkottary thanks! So I guess this was caused by the registrator assuming the name of the main branch was "master"?
