### ISSUE TITLE
Animation in tilted bottom boundary layer example doesn't work in the docs when the grid is stretched

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#159]
This is a problem that popped up in https://github.com/tomchor/Oceanostics.jl/pull/157 and I haven't been able to fix it.

Basically when the grid there is stretched, the docs hang at the point where the animation is being created.
- This does not happen when running the example locally (i.e. everything works without issues)
- And this issue does not happen with a regular grid.

So for now https://github.com/tomchor/Oceanostics.jl/pull/157 re-wrote the example using a regular grid and things seems to be working properly. I believe the problem is either in the interaction between Documenter and Makie or in the interaction between Documenter and Rasters.

What makes it hard to investigate this is that I wasn't able to reproduce it locally at all :/
So for each iteration I've been having to make a change, commit, push it to a PR, wait for about an hour for the docs to get there and see the CI hangs. I think the next step is to make a MWE with an animation without Rasters, to at least narrow down if the issue is with Makie + Documenter, or Rasters + Documenter.

**Comment by glwagner** [comment]
Maybe try speeding up the docs build in CI by commenting everything out except this one example in `make.jl`.

**Comment by tomchor** [comment]
I've done that in the course of #157, but it's slow since there's no error, so it forces me to wait for a longer-than-usual amount of time to see if indeed nothing is happening.

**Comment by glwagner** [comment]
You mean even with only one example being loaded the docs still take an hour to run? 😱

**Comment by glwagner** [comment]
Can you paste the code that creates the animation?

**Comment by tomchor** [comment]
Here!:

https://github.com/tomchor/Oceanostics.jl/blob/2036fe3780efb6e8a8b7d386e506da446be976bf/docs/examples/tilted_bottom_boundary_layer.jl#L167-L218

**Comment by glwagner** [comment]
Huh, I'm not familiar with the packages being used. It seems probable that the relative slowdown for stretched vs uniform vertical grid has to do with `:zF => Z`. What's `Z`?
