### ISSUE TITLE
Suggestions for tagging releases, etc.

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#2]
Since apparently LESbrary.jl will depend on Oceanostics.jl, I'm thinking it would be good to have some sort of version tagging or something to help maintain both packages and its dependencies properly, no? Maybe even one of automatic tools that github provides.

I've maintained packages before (including version tagging) but they were always for personal use. @ali-ramadhan @glwagner 
 Since you guys have experience with that, do you have any tips?

**Comment by glwagner** [comment]
I think it makes sense to liberally bump the release number often. You could tag a minor version every time a diagnostic is added, perhaps.

Could also make sense to register with the julia package registry so you can use the julia registrator bot:

https://github.com/JuliaRegistries/Registrator.jl

**Comment by ali-ramadhan** [comment]
I agree it would make sense to register Oceanostics.jl as a Julia package.

I had some issues setting up multiple environments in https://github.com/CliMA/LESbrary.jl/pull/93 I think because Oceanostics.jl wasn't a registered package.

I think having CI is a requirement for registering a Julia package but I can help with setting up a GitHub Actions CI pipeline if needed.

**Comment by tomchor** [comment]
I actually tried [registering it last week](https://github.com/JuliaRegistries/General/pull/30767). The two limiting factors were:

- I need to provide and upper bound to `[compat]`. This is easily doable but I decided not to do it in the case of Oceananigans the versions change so quickly. I'd need to update the upper bound weekly. (Unless maybe I just set it to 1.0? Not sure if that would work and it's probably not recommended)
- Adding tests (which I have no idea how to do for the time being)

I didn't do much effort back then because I thought it would mostly impact me. But since you guys are having issues because of it, it might make sense to make an effort.

**Comment by ali-ramadhan** [comment]
Ah should I open a PR to start adding tests?

I think for package registeration a very simple `runtests.jl` file with `using Oceanostics` should suffice (and would at least make sure the package is usable).

**Comment by tomchor** [comment]
> Ah should I open a PR to start adding tests?

Sure! And I truly appreciate it. Should I make you a collaborator to make things easier?

**Comment by ali-ramadhan** [comment]
Ah that might help just for this PR since I don't think GitHub Actions will run on PRs from forks?

**Comment by tomchor** [comment]
Very true! Just sent you an invitation :)

**Comment by tomchor** [comment]
Done! I think everything worked out:. Thanks for the help! 

https://github.com/JuliaRegistries/General/pull/31318
