### ISSUE TITLE
Change every `KernelComputedField` to `KernelFunctionOperation`

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#21]
@glwagner do you see any problems downsides for this? If I understand correctly the migration will only bring upsides:

- Simpler (no need for `@kernel` and `@index`)
- KernelAbstrations won't be a dependence anymore
- Resulting quantities are abstract operations, which are more flexible

**Comment by glwagner** [comment]
I don't see any downsides. You'll only need `KernelComputedField` to do fairly non-trivial things in a kernel like unroll loops, etc.

**Comment by tomchor** [comment]
Good. Then I'll probably start some migration soon.

I haven't used `KernelFunctionOperation` so I'm not familiar, but I guess if we use user-facing constructors they would return the operation itself, right? (They wouldn't return, for example, a `ComputedField` based on the operation, right?)

**Comment by glwagner** [comment]
Hrmm yeah I think the minimal / easy to maintain API returns the operations and let users build `ComputedField` or `AveragedField` according to their needs.
