### ISSUE TITLE
Including a fancier progress messenger

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#23]
@glwagner @ali-ramadhan Would you be opposed that I copy [this very useful progress messenger](https://github.com/CliMA/LESbrary.jl/blob/master/src/Utils/progress_messenger.jl) to Oceanostics.jl?

The rationale is that I think the `wall_time_per_step` feature is super-useful, but currently it only works for LES (since it's in LESbrary). I'd like to make a version of it here that works for both (kinda like what I did [here](https://github.com/tomchor/Oceanostics.jl/blob/main/src/progress_messengers.jl)).

After that you can even delete that progress messenger from LESbrary and use the one from Oceanostics.

Thoughts?

**Comment by glwagner** [comment]
Seems legit. Or maybe it belongs in Oceananigans?

**Comment by tomchor** [comment]
We can discuss this further or take a vote with other contributors, but I think Oceananigans is a pretty big package already. So my tendency has been to try to not add more stuff to it unless necessary.

So for example, I was thinking of adding utilities stuff like progress messengers, sponge layers, to other packages. I think Oceanostics is a good candidate.
