### ISSUE TITLE
Provide convenience constructors for KernelComputedFields?

### ISSUE THREAD

**Issue by glwagner** [tomchor/Oceanostics.jl#4]
It could make sense to provide constructors for `KernelComputedField`s corresponding to the kernels in this package, since, for example, the kernel

https://github.com/tomchor/Oceanostics.jl/blob/e3d087f25a717662b00e12c68989f409b471913c/src/TurbulentKineticEnergyTerms.jl#L11-L19

is specific to the location `Center, Center, Center`. Thus providing constructors that look something like

```julia
KineticEnergy(arch, grid, u, v, w; kwargs...) = KernelComputedField(Center, Center, Center, kinetic_energy_ccc!, arch, grid; computed_dependencies=(u, v, w), kwargs...)
```

that enforce correct locations might be useful to users and will alleviate some users from the need to have detailed knowledge of the staggered grid.

**Comment by tomchor** [comment]
I like that idea. The only issue that I can see is that in future we might want to add these calculations for different locations for whatever reason. For example we might wanna add `kinetic_energy_ffc!` (Meaning `(Face, Face, Center)`.)

Would it make it sense to make a wrapper function to keep the option of specifying the location?

**Comment by glwagner** [comment]
When/if new kernels are added that perform computations at different locations you could potentially write something (kinda silly) like

```julia
first_letter(loc) = lowercase(string(loc))

function KineticEnergy(arch, grid, u, v, w, location = (Center, Center, Center), kwargs...)
    location_code = Symbol(Tuple(first_letter(loc) for loc in location)...)
    kernel_name = Symbol(:kinetic_energy_, location_code, :!)
    kernel = @eval $kernel_name
    return KernelComputedField(location..., kernel, arch, grid; computed_dependencies=(u, v, w), kwargs...)
end
```

(or you can just hard-code the options for output location).

**Comment by glwagner** [comment]
The first three lines parse the location to get the kernel name, eg:

```julia
julia> random_function_ccc!(args...) = nothing
random_function_ccc! (generic function with 1 method)

julia> location_code = Symbol("c", "c", "c")
:ccc

julia> kernel_name = Symbol(:random_function_, location_code, :!)
:random_function_ccc!

julia> kernel = @eval $kernel_name
random_function_ccc! (generic function with 1 method)
```

**Comment by tomchor** [comment]
I included a few of these constructors: https://github.com/tomchor/Oceanostics.jl/blob/86039760d562182fc03bdc770faaed26a74736e3/src/TurbulentKineticEnergyTerms.jl#L23-L30

I generally like these meta-programming styles like you suggested, but I preferred the hard-coding approach here because (1) it's way clearer, and (2) I believe that we won't have many different kinds of kernels anyway.

Feel free to contribute with more. I'll be adding those as they become useful to me in particular.

**Comment by glwagner** [comment]
You can also use dispatch if you are worried about code clarity:

```julia
kinetic_energy_kernel(::Type{Center}, ::Type{Center}, ::Type{Center}) = kinetic_energy_ccc!
kinetic_energy_kernel(::Type{Face, ::Type{Center}, ::Type{Center}) = kinetic_energy_fcc!

KineticEnergy(model, u, v, w, location = (Center, Center, Center), kwargs...) =
    KernelComputedField(Center, Center, Center, kinetic_energy_kernel(location...), model; computed_dependencies=(u, v, w), kwargs...) 
```
