### ISSUE TITLE
Should we change the way compat with Ocenanigans is dealt with?

### ISSUE THREAD

**Issue by tomchor** [tomchor/Oceanostics.jl#64]
At the moment the compat entry for Oceananigans is done like this: https://github.com/tomchor/Oceanostics.jl/blob/5c4288cf84f49130fbbf1c409e24ce1082a18d37/Project.toml#L10-L11

SInce Oceananigans releases minor versions so fast though (much more often than Oceanostics) generally the `compat` entry has to be updated fairly often, but it'll take a while for that `compat` update to be included in the tagged release. This means that if a user has the most up-to-date Oceananigans and tries to install Oceanostics with `] add Oceanostics`, often Oceananigans gets downgraded. For example in the example below, since the tagged version only works with Ocenanigans 0.68:

```julia
(AGUOSM22-LES-tutorial) pkg> add Oceanostics
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
   Installed Oceanostics ── v0.6.3
   Installed Plots ──────── v1.25.7
   Installed Oceananigans ─ v0.68.7
    Updating `~/repos/AGUOSM22-LES-tutorial/Project.toml`
  [033835bb] ↑ JLD2 v0.4.15 ⇒ v0.4.19
  [9e8cae18] ↓ Oceananigans v0.69.2 ⇒ v0.68.7
  [d0ccf422] + Oceanostics v0.6.3
  [91a5bcdd] ↑ Plots v1.25.0 ⇒ v1.25.7
    Updating `~/repos/AGUOSM22-LES-tutorial/Manifest.toml`
  [28b8d3ca] ↑ GR v0.62.1 ⇒ v0.63.1
  [033835bb] ↑ JLD2 v0.4.15 ⇒ v0.4.19
  [9e8cae18] ↓ Oceananigans v0.69.2 ⇒ v0.68.7
  [d0ccf422] + Oceanostics v0.6.3
  [91a5bcdd] ↑ Plots v1.25.0 ⇒ v1.25.7
  [01d81517] ↑ RecipesPipeline v0.4.1 ⇒ v0.5.0
  [05181044] + RelocatableFolders v0.1.3
  [41fe7b60] + Unzip v0.1.2
Precompiling project...
  ✓ RecipesPipeline
  ✓ Oceananigans
  ✓ Plots
  4 dependencies successfully precompiled in 38 seconds (182 already precompiled)
  3 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions
```

This isn't too bad, and the user can avoid this by installing Oceanostics straight from the main branch of the git repo (and hope that the `compat` entry is up-to-date) but I wonder if we should do things differently.

I can think of two options:

1 - Re-write the `compat` entry in a way that prevents us from having to update it often. Like `^0` or preemptive putting in versions that don't exist yet like `0.86-0.99`. I don't like this option very much because it isn't strictly correct and might cause compatibility problems in the future.
2 - Release a patched version every time Oceananigans tags a new minor (and thus whenever our `compat` entry gets updated). It's a bit annoying but I think this is the most correct route.
3 - We can also keep it the way it is and indicate clearly in the README that users should install the package from git if they want to be able to use the latest Oceananigans.

Thoughts?

**Comment by glwagner** [comment]
Am I interpreting the CompatHelper docstring correctly that there is an option to `bump_version` whenever compat is updated?

https://juliaregistries.github.io/CompatHelper.jl/dev/#CompatHelper.main

That might make 2 a bit easier.

I wonder if "version explosion" via dependencies is a reason not to update `Oceananigans` as often.

**Comment by tomchor** [comment]
> Am I interpreting the CompatHelper docstring correctly that there is an option to `bump_version` whenever compat is updated?
> 
> https://juliaregistries.github.io/CompatHelper.jl/dev/#CompatHelper.main
> 
> That might make 2 a bit easier.

Just to make sure I understand, you're talking about replacing the line https://github.com/JuliaRegistries/CompatHelper.jl/blob/1b46ec02d86b239a5deca294c2ef73816dbab099/.github/workflows/CompatHelper.yml#L27

with `CompatHelper.main(bump_version=true)`?


> I wonder if "version explosion" via dependencies is a reason not to update `Oceananigans` as often.

I don't really have an opinion here, but I thought Oceanostics was the only package that depends on Oceananigans that gets frequent updates, no?

**Comment by glwagner** [comment]
> Just to make sure I understand, you're talking about replacing the line https://github.com/JuliaRegistries/CompatHelper.jl/blob/1b46ec02d86b239a5deca294c2ef73816dbab099/.github/workflows/CompatHelper.yml#L27
> 
> with `CompatHelper.main(bump_version=true)`? If so I agree with you. Seems like it would help things.

I didn't know where `CompatHelper.main` was called, but it looks like you found it. Your suggestion looks like it might work.

> > I wonder if "version explosion" via dependencies is a reason not to update `Oceananigans` as often.
> 
> I don't really have an opinion here, but I thought Oceanostics was the only package that depends on Oceananigans that gets frequent updates, no?

I don't know how many packages / people depend on Oceananigans. But whatever the situation is now, we want to develop best practices that make life easier for our community.

**Comment by tomchor** [comment]
I think the CompatHelper solution is worth a shot. I'll open a  PR

**Comment by glwagner** [comment]
I guess it's worth mentioning for documentation's sake that we do know of other packages that depend on Oceananigans now:

* https://github.com/CliMA/OceanTurbulenceParameterEstimation.jl
* https://github.com/CliMA/ClimaSimulations.jl
* https://github.com/CliMA/LESbrary.jl
* https://github.com/CliMA/ClimaSimulations.jl (for now)

Things might change in the future. I think we probably want to split off the core functionality of `Oceananigans` into a different package (eg `StaggeredVolumes.jl`). At that point versioning might become a little more sane (`Oceanostics` might depend on `StaggeredVolumes.jl` rather than `Oceananigans.jl`).

**Comment by tomchor** [comment]
> I guess it's worth mentioning for documentation's sake that we do know of other packages that depend on Oceananigans now:
> 
> * https://github.com/CliMA/OceanTurbulenceParameterEstimation.jl
> * https://github.com/CliMA/ClimaSimulations.jl
> * https://github.com/CliMA/LESbrary.jl
> * https://github.com/CliMA/ClimaSimulations.jl (for now)

Is `ClimaSimulations.jl` mentioned twice by accident?


> Things might change in the future. I think we probably want to split off the core functionality of `Oceananigans` into a different package (eg `StaggeredVolumes.jl`). At that point versioning might become a little more sane (`Oceanostics` might depend on `StaggeredVolumes.jl` rather than `Oceananigans.jl`).

Yeah I think that's a nice way to go.
