### ISSUE TITLE
Progress messenger improvements

### ISSUE THREAD

**Issue by glwagner** [tomchor/Oceanostics.jl#69]
Bit of a catch-all issue:

1. Both `SimpleProgressMessenger` and `SingleLineProgressMessenger` are `TitleCase` but don't actually return objects. Let's fix this because it can mislead people (me, for example)
2. There's much shared code between the progress messengers. 3x copy/paste makes it 3x harder to improve the code. #68 helps a bit but there's still some to do.

**Comment by tomchor** [comment]
Agreed!

I've thought about the amount of shared code between progress messengers, but couldn't figure out a good solution yet. I like what you did in #68 though.
